parse_git_branch() {
  git branch --show-current 2>/dev/null
}

PS1='\[\e[32m\]\u@\h\[\e[34m\]:\w\[\e[0m\]\n\[\e[36m\]➜ \[\e[0m\]$(if [ -n "$(parse_git_branch)" ]; \
  then echo "\[\e[33m\][$(parse_git_branch)\[\e[33m\]]"\[\e[0m\]; fi)\$ '
